version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    networks:
      - app-tier
    ports:
      - 6379:6379

  redis-slave-1:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_REPLICA_IP=52.130.155.192
      - REDIS_REPLICA_PORT=6380
    ports:
      - 6380:6379
    depends_on:
      - redis
    networks:
      - app-tier

  redis-slave-2:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_REPLICA_IP=52.130.155.192
      - REDIS_REPLICA_PORT=6381
    ports:
      - 6381:6379
    depends_on:
      - redis
    networks:
      - app-tier

  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_MASTER_HOST=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_IP=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_PORT=26379
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26379:26379
    networks:
      - app-tier
      
  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_MASTER_HOST=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_IP=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_PORT=26380
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26380:26379
    networks:
      - app-tier

  redis-sentinel-3:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_MASTER_HOST=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_IP=52.130.155.192
      - REDIS_SENTINEL_ANNOUNCE_PORT=26381
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26381:26379
    networks:
      - app-tier

